#!/bin/bash

function gyp_help() {
  echo "to install gyp:"
  echo "cd ~/your_workspace/"
  echo "git clone git@github.com:anki/anki-gyp.git"
  echo "echo PATH=$HOME/your_workspace/gyp:\$PATH >> ~/.bash_profile"
  echo ". ~/.bash_profile"
}

#location of this script
SRCDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $SRCDIR

#root of the git project
GIT=`which git`
if [ -z $GIT ]; then
  echo git not found
  exit 1
fi
TOPLEVEL=`$GIT rev-parse --show-toplevel`

GYP=`which gyp`
if [ -z $GYP ]; then
  echo gyp not found
  gyp_help
  exit 1
  echo $GYP
fi

$GYP --version | grep ANKI > /dev/null 2>&1

if [ $? -ne 0 ]; then
  echo incorrect version of gyp installed
  gyp_help
  exit 1
fi

# mac
#################### GYP_DEFINES ####
DEFINES=" lua_library_type=static_library
        "
GYP_DEFINES=${DEFINES} gyp lua.gyp --check --depth . -f xcode --generator-output=./output/mac



# ios
#################### GYP_DEFINES ####
DEFINES=" lua_library_type=static_library
          OS=ios
        "
GYP_DEFINES=${DEFINES} gyp lua.gyp --check --depth . -f xcode --generator-output=./output/ios



# android
#################### GYP_DEFINES ####
DEFINES=" lua_library_type=static_library
          os_posix=1
          OS=android
          target_arch=arm
          clang=1
          component=static_library
          use_system_stlport=0
        "

# android generator does not support --generator-output
GYP_DEFINES=${DEFINES} ANDROID_BUILD_TOP=SRCDIR gyp lua.gyp --check --depth . -f android-make 

# fix the path scope of the android make file
/bin/cat > $SRCDIR/output/lua/jni/Android.mk << "END_OF_LOCAL_PATH_FIX"
# do not edit, generated by gyp
LUA_PROJECT_PATH:= $(realpath $(join $(dir $(call this-makefile)), /../../../.. ))
#LUA_PROJECT_PATH:= $(LUA_PROJECT_PATH)/lua-5.2.2/src
#$(warning $(LUA_PROJECT_PATH))
# set local compilation path
LOCAL_PATH:= $(LUA_PROJECT_PATH)
# from GypAndroid.mk:
GYP_CONFIGURATION ?= Default
END_OF_LOCAL_PATH_FIX

# add gyp generated data
# we might have to rename target from 'lua_gyp' to 'lua'
/bin/cat $SRCDIR/lua.target.mk >> $SRCDIR/output/lua/jni/Android.mk
#remove leftover junk
/bin/rm $SRCDIR/lua.target.mk $SRCDIR/GypAndroid.mk
